

services:
  db:
    image: postgres:16-alpine
    container_name: crypto_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: crypto
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl_app:
    build: .
    container_name: binance_etl
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /app/.venv/
      - /app/binancenv/
    command: ["--symbol", "BTCUSDT", "ETHUSDT", "BNBUSDT", "--output", "postgres"]


volumes:
  postgres_data:
